window.COLLECTION_DATA = [
  {
    id: 1,
    category: 'mens-soccer',
    number: '#10',
    playerName: 'Alphonso Davies',
    team: 'Bayern Munich',
    year: '2024',
    variant: 'variant-holo',
    badge: 'AUTO /25',
    badgeClass: '',
    condition: 'MINT',
    grade: 'PSA 10',
    printRun: '/25'
  },
  {
    id: 2,
    category: 'mens-soccer',
    number: '#7',
    playerName: 'Cristiano Ronaldo',
    team: 'Al Nassr',
    year: '2023',
    variant: 'variant-gold',
    badge: 'PSA 10',
    badgeClass: 'badge-psa',
    condition: 'GEM MINT',
    grade: 'PSA 10',
    printRun: 'BASE'
  },
  {
    id: 3,
    category: 'mens-soccer',
    number: '#9',
    playerName: 'Erling Haaland',
    team: 'Man City',
    year: '2022',
    variant: 'variant-blue',
    badge: 'RC',
    badgeClass: 'badge-rc',
    condition: 'NM-MT',
    grade: 'RAW',
    printRun: '/99'
  },
  {
    id: 4,
    category: 'mens-soccer',
    number: '#15',
    playerName: 'Kylian Mbappé',
    team: 'PSG',
    year: '2023',
    variant: 'variant-holo',
    badge: 'PSA 9',
    badgeClass: 'badge-psa',
    condition: 'MINT',
    grade: 'PSA 9',
    printRun: '/50'
  },
  {
    id: 5,
    category: 'mens-soccer',
    number: '#6',
    playerName: 'Vinícius Júnior',
    team: 'Real Madrid',
    year: '2024',
    variant: 'variant-blue',
    badge: 'PSA 10',
    badgeClass: 'badge-psa',
    condition: 'GEM MINT',
    grade: 'PSA 10',
    printRun: 'BASE'
  },
  {
    id: 6,
    category: 'womens-soccer',
    number: '#11',
    playerName: 'Sam Kerr',
    team: 'Chelsea',
    year: '2024',
    variant: 'variant-gold',
    badge: 'PSA 9',
    badgeClass: 'badge-psa',
    condition: 'NM-MT',
    grade: 'PSA 9',
    printRun: '/75'
  },
  {
    id: 7,
    category: 'womens-soccer',
    number: '#14',
    playerName: 'Alex Morgan',
    team: 'USWNT',
    year: '2023',
    variant: 'variant-holo',
    badge: 'RC /99',
    badgeClass: '',
    condition: 'NM-MT',
    grade: 'RAW',
    printRun: '/99'
  },
  {
    id: 8,
    category: 'womens-soccer',
    number: '#8',
    playerName: 'Mia Hamm',
    team: 'Legend',
    year: '2020',
    variant: 'variant-blue',
    badge: 'PSA 8',
    badgeClass: 'badge-psa',
    condition: 'NM',
    grade: 'PSA 8',
    printRun: '/10'
  },
  {
    id: 9,
    category: 'womens-soccer',
    number: '#9',
    playerName: 'Megan Rapinoe',
    team: 'USWNT',
    year: '2023',
    variant: 'variant-gold',
    badge: 'PSA 9',
    badgeClass: 'badge-psa',
    condition: 'MINT',
    grade: 'PSA 9',
    printRun: '/50'
  },
  {
    id: 10,
    category: 'other-sports',
    number: '#23',
    playerName: 'LeBron James',
    team: 'Lakers',
    year: '2022',
    variant: 'variant-holo',
    badge: 'PSA 10',
    badgeClass: 'badge-psa',
    condition: 'GEM MINT',
    grade: 'PSA 10',
    printRun: '/25'
  },
  {
    id: 11,
    category: 'other-sports',
    number: '#10',
    playerName: 'Lionel Messi',
    team: 'Inter Miami',
    year: '2024',
    variant: 'variant-gold',
    badge: 'AUTO /10',
    badgeClass: '',
    condition: 'MINT',
    grade: 'PSA 10',
    printRun: '/10'
  },
  {
    id: 12,
    category: 'other-sports',
    number: '#1',
    playerName: 'Patrick Mahomes',
    team: 'Chiefs',
    year: '2023',
    variant: 'variant-blue',
    badge: 'RC /99',
    badgeClass: 'badge-rc',
    condition: 'NM-MT',
    grade: 'RAW',
    printRun: '/99'
  },
  {
    id: 13,
    category: 'other-sports',
    number: '#44',
    playerName: 'Shohei Ohtani',
    team: 'Dodgers',
    year: '2024',
    variant: 'variant-holo',
    badge: 'PSA 9',
    badgeClass: 'badge-psa',
    condition: 'NM-MT',
    grade: 'PSA 9',
    printRun: '/75'
  },
  {
    id: 14,
    category: 'tcg',
    number: '#001',
    playerName: 'Charizard',
    team: 'Pokémon',
    year: '1999',
    variant: 'variant-gold',
    badge: 'PSA 8',
    badgeClass: 'badge-psa',
    condition: 'NM',
    grade: 'PSA 8',
    printRun: 'Base Set'
  },
  {
    id: 15,
    category: 'tcg',
    number: '#103',
    playerName: 'Black Lotus',
    team: 'MTG',
    year: '1993',
    variant: 'variant-blue',
    badge: 'PSA 7',
    badgeClass: 'badge-psa',
    condition: 'NM-MT',
    grade: 'PSA 7',
    printRun: 'Limited'
  },
  {
    id: 16,
    category: 'tcg',
    number: '#25',
    playerName: 'Blue Eyes',
    team: 'Yu-Gi-Oh',
    year: '2002',
    variant: 'variant-holo',
    badge: 'RAW',
    badgeClass: '',
    condition: 'MINT',
    grade: 'RAW',
    printRun: '1st Ed'
  },
  {
    id: 17,
    category: 'tcg',
    number: '#001',
    playerName: 'Pikachu Illustrator',
    team: 'Pokémon',
    year: '1998',
    variant: 'variant-gold',
    badge: 'PSA 9',
    badgeClass: 'badge-psa',
    condition: 'MINT',
    grade: 'PSA 9',
    printRun: 'Promo'
  }
];
